# Generated by Django 4.1.3 on 2022-12-23 23:53

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('url_foto', models.ImageField(blank=True, null=True, upload_to='usuarios/cliente/%Y/%m/%d/')),
                ('cpf', models.CharField(max_length=15)),
                ('capa_foto', models.ImageField(blank=True, null=True, upload_to='usuarios/cliente/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('CEP', models.CharField(max_length=9)),
                ('numero', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Freteiro',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('url_foto', models.ImageField(blank=True, null=True, upload_to='usuarios/freteiro/%Y/%m/%d/')),
                ('cpf', models.CharField(max_length=15)),
                ('capa_foto', models.ImageField(blank=True, null=True, upload_to='usuarios/freteiro/%Y/%m/%d/')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plataform.endereco')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CA', 'Cancelado'), ('EN', 'Em negociação'), ('AG', 'Aguardando coleta'), ('TR', 'Em trânsito'), ('CO', 'Concluído')], default='EN', max_length=2)),
                ('observacao', models.CharField(blank=True, max_length=300, null=True)),
                ('nomeDestinatario', models.CharField(max_length=200)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_coleta', models.DateField()),
                ('data_entrega', models.DateField()),
                ('turno_entrega', models.CharField(choices=[('TA', 'Tarde'), ('MA', 'Manhã'), ('NO', 'Noite')], max_length=2)),
                ('turno_coleta', models.CharField(choices=[('TA', 'Tarde'), ('MA', 'Manhã'), ('NO', 'Noite')], max_length=2)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.cliente')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_endereco_destino', to='plataform.endereco')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_endereco_origem', to='plataform.endereco')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem_url', models.ImageField(blank=True, null=True, upload_to='produto/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_foto', models.ImageField(blank=True, null=True, upload_to='veiculo')),
                ('placa', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('ano', models.CharField(max_length=4)),
                ('freteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.freteiro')),
                ('tipo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.tipoveiculo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('eh_aceita', models.BooleanField(default=False)),
                ('ehNegada', models.BooleanField(default=False)),
                ('contraproposta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plataform.proposta')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.veiculo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_veiculo',
            field=models.ManyToManyField(to='plataform.tipoveiculo'),
        ),
        migrations.CreateModel(
            name='AvaliacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('observacao', models.TextField()),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliado', to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
