# Generated by Django 4.1.5 on 2023-01-20 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0001_initial'),
    ]

    operations = [
        # # TODO - Isso não funciona no postgres
        # migrations.RunSQL("""
        #     CREATE TRIGGER LogPedidoTrigger
        #     AFTER INSERT
        #     ON plataform_pedido
        #     BEGIN
        #         INSERT INTO plataform_log(data) VALUES (current_timestamp);
        #     END;
        # """)
    ]
