# Generated by Django 4.1.3 on 2022-11-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='freteiro',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='proposta',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tipoveiculo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='turno_coleta',
            field=models.CharField(choices=[('TA', 'Tarde'), ('MA', 'Manhã'), ('NO', 'Noite')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='turno_entrega',
            field=models.CharField(choices=[('TA', 'Tarde'), ('MA', 'Manhã'), ('NO', 'Noite')], max_length=2),
        ),
    ]
