# Generated by Django 4.1.3 on 2022-11-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0002_alter_cliente_options_alter_endereco_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
