# Generated by Django 4.1.3 on 2023-01-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0002_alter_proposta_contraproposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposta_set', to='plataform.pedido'),
        ),
    ]
