# Generated by Django 4.1.5 on 2023-01-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0003_alter_proposta_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='is_contraproposta',
            field=models.BooleanField(default=False),
        ),
    ]
