# Generated by Django 4.1.3 on 2022-12-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0003_alter_endereco_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='url_foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/cliente/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='freteiro',
            name='url_foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/freteiro/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observacao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_url',
            field=models.ImageField(blank=True, null=True, upload_to='produto/%Y/%m/%d/'),
        ),
    ]
