# Generated by Django 4.1.2 on 2022-12-18 01:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataform', '0004_alter_cliente_url_foto_alter_freteiro_url_foto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposta',
            old_name='ehAceita',
            new_name='eh_aceita',
        ),
        migrations.AddField(
            model_name='cliente',
            name='capa_foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/cliente/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='freteiro',
            name='capa_foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/freteiro/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='AvaliacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('observacao', models.TextField()),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliado', to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
