# Generated by Django 4.1.2 on 2022-12-22 16:38

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0005_rename_ehaceita_proposta_eh_aceita_cliente_capa_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
    ]
