# CRA
FROM node:alpine as build-deps
WORKDIR /code
COPY frontend /code/
RUN npm install
RUN npm run build

# Nginx
FROM nginx:1.12-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY frontend/nginx.conf /etc/nginx/conf.d/
COPY --from=build-deps /code/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

