# Generated by Django 4.0.4 on 2022-07-31 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0002_proposta_ehnegada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='ehNegada',
        ),
    ]
