# Generated by Django 4.0.4 on 2022-07-02 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('CEP', models.CharField(max_length=9)),
                ('numero', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300)),
                ('nomeDestinatario', models.CharField(max_length=200)),
                ('dataColeta', models.DateField()),
                ('dataEntrega', models.DateField()),
                ('turnoColeta', models.CharField(max_length=6)),
                ('turnoEntrega', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem_url', models.ImageField(blank=True, null=True, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('url_foto', models.ImageField(blank=True, null=True, upload_to=None)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cpf', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=30)),
                ('ehModerador', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plataform.usuario')),
            ],
            bases=('plataform.usuario',),
        ),
        migrations.CreateModel(
            name='Freteiro',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plataform.usuario')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plataform.endereco')),
            ],
            bases=('plataform.usuario',),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('ano', models.CharField(max_length=4)),
                ('tipo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.tipoveiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('ehAceita', models.BooleanField(default=False)),
                ('ehContraproposta', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.usuario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.veiculo')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='Produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.status'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.endereco'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_veiculo',
            field=models.ManyToManyField(to='plataform.tipoveiculo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='freteiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.freteiro'),
        ),
    ]
