# Generated by Django 4.0.4 on 2022-06-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('url_foto', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cpf', models.CharField(max_length=15)),
                ('senha', models.IntegerField(verbose_name='Senha')),
                ('ehModerador', models.BooleanField()),
            ],
        ),
    ]
