# Generated by Django 4.0.4 on 2022-07-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='ehNegada',
            field=models.BooleanField(default=False),
        ),
    ]
