# Generated by Django 4.1 on 2022-08-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_url',
            field=models.ImageField(blank=True, null=True, upload_to='produto'),
        ),
    ]
