# Generated by Django 4.0.6 on 2022-07-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='freteiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataform.freteiro'),
        ),
    ]
