# Generated by Django 4.0.4 on 2022-06-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0002_alter_usuario_ehmoderador_alter_usuario_url_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=30),
        ),
    ]
