# Generated by Django 4.0.4 on 2022-06-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0003_alter_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plataform.usuario')),
            ],
            bases=('plataform.usuario',),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('CEP', models.CharField(max_length=9)),
                ('numero', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='url_foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('ano', models.DateField()),
                ('tipo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.tipoveiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300)),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.produto')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.status')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.endereco')),
                ('tipo_veiculo', models.ManyToManyField(to='plataform.tipoveiculo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Freteiro',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plataform.usuario')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plataform.endereco')),
            ],
            bases=('plataform.usuario',),
        ),
    ]
