# Generated by Django 4.0.4 on 2022-07-31 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0003_pedido_temproposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='temProposta',
        ),
    ]
