# Generated by Django 4.0.4 on 2022-06-25 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0004_cliente_endereco_produto_status_tipoveiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('ehAceita', models.BooleanField(default=False)),
                ('ehContraproposta', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.usuario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.veiculo')),
            ],
        ),
    ]
