# Generated by Django 4.0.4 on 2022-06-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0005_proposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_url',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='url_foto',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
