# Generated by Django 4.0.4 on 2022-06-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0006_alter_produto_imagem_url_alter_usuario_url_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.CharField(max_length=4),
        ),
    ]
